{{- define "mongodb.secret" }}
{{- range $index, $webhook := $.Values.instances }}
{{- $mongoAdminPasswd := (randAlphaNum 10) | quote }}
{{- $mongoPasswd := (randAlphaNum 10) | quote }}
{{- $mongoUser := (randAlpha 10) | quote }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace "mongodb-{{ .app_name }}") }}
{{- if $secret }}
{{- $mongoAdminPasswd = index $secret.data "MONGODB_ADMIN_PASSWORD" }}
{{- $mongoPasswd = index $secret.data "MONGODB_PASSWORD" }}
{{- $mongoUser = index $secret.data "MONGODB_USER" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: "mongodb-{{ .app_name }}"
  name: "mongodb-{{ .app_name }}"
stringData:
  MONGODB_ADMIN_PASSWORD: {{ $mongoAdminPasswd }}
  MONGODB_DATABASE: "mongodb-{{ .app_name }}"
  MONGODB_PASSWORD: {{ $mongoPasswd }}
  MONGODB_USER: {{ $mongoUser }}
  MONGODB_SERVICE_HOST: "mongodb-{{ .app_name }}"
{{- end }}
{{- end }}
