{{- define "mongodbs.service" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .app_name }}
  name: {{ .app_name }}
spec:
  ports:
  - name: http
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app.kubernetes.io/name: {{ .app_name }}
    deploymentconfig: {{ .app_name }}
  type: ClusterIP
{{- end }}
